name: Go

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20' # Utiliza una versi칩n m치s reciente de Go, como '1.17' o '1.16'

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o PlanificadorEquitativo
        working-directory: ./

      - name: Upload Linux PlanificadorEquitativo
        uses: actions/upload-artifact@v3
        with:
          name: PlanificadorEquitativo
          path: ./PlanificadorEquitativo
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20' # Utiliza una versi칩n m치s reciente de Go, como '1.17' o '1.16'
        
      - name: Build for Windows
        run: |
          $env:GOOS="windows"
          $env:GOARCH="amd64"
          go build -o PlanificadorEquitativo.exe
        working-directory: ./

      - name: Upload Windows PlanificadorEquitativo
        uses: actions/upload-artifact@v3
        with:
          name: PlanificadorEquitativo
          path: ./PlanificadorEquitativo.exe
 
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
