name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20 # Reemplaza con la versión de Go que desees

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o PlanificadorEquitativo main.go
        working-directory: ./path/to/your/app

      - name: Upload Linux PlanificadorEquitativo
        uses: actions/upload-artifact@v2
        with:
          name: PlanificadorEquitativo
          path: ./path/to/your/app/myapp-linux

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x # Reemplaza con la versión de Go que desees

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o PlanificadorEquitativo.exe main.go
        working-directory: ./path/to/your/app

      - name: Upload Windows PlanificadorEquitativo
        uses: actions/upload-artifact@v2
        with:
          name: PlanificadorEquitativo
          path: ./path/to/your/app/PlanificadorEquitativo.exe
