name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' # Utiliza una versi칩n m치s reciente de Go, como '1.17' o '1.16'

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o PlanificadorEquitativo
        working-directory: ./

      - name: Upload Linux PlanificadorEquitativo
        uses: actions/upload-artifact@v2
        with:
          name: PlanificadorEquitativo
          path: ./PlanificadorEquitativo

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' # Utiliza una versi칩n m치s reciente de Go, como '1.17' o '1.16'

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o PlanificadorEquitativo.exe
        working-directory: ./

      - name: Upload Windows PlanificadorEquitativo
        uses: actions/upload-artifact@v2
        with:
          name: PlanificadorEquitativo
          path: ./PlanificadorEquitativo.exe
